language: python
python:
    - "3.4"
    - "3.6"
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt update
install:
    - sudo apt install -y gcc-4.8
    - pip install flake8 cpplint
script:
    - flake8
    - gcc --version
    - cpplint --quiet --recursive --filter="-legal/copyright,-runtime/int,-runtime/arrays" .
    - ./check_tags.sh
    - ./run_all.sh
notifications:
    email:
        - arcursino@gmail.com
